// Generated by CoffeeScript 1.9.0
module.exports = function(robot) {
  return robot.hear(/^(.+)\+\+$/i, function(msg) {
    var user;
    user = msg.match[1];
    if (!robot.brain.data[user]) {
      robot.brain.data[user] = 0;
    }
    robot.brain.data[user]++;
    robot.brain.save();
    return msg.send(robot.brain.data[user]);
  });
};
