// Generated by CoffeeScript 1.9.0
module.exports = function(robot) {
  robot.enter(function(msg) {
    msg.message.user.name;
    return msg.send("おはよう " + msg.message.user.name + "さん♪");
  });
  return robot.leave(function(msg) {
    return msg.send("@" + msg.message.user.name + " 今日も一日お疲れ様やんな♪");
  });
};
